"use client";

import { create } from "zustand";

const DEFAULT_EDITOR = `## New Project
Waiting for input...
Upload a document or describe your physics topic to begin.
`;

const DEFAULT_VARS = { Scene_Mode: -1 };

function uid() {
  return Math.random().toString(16).slice(2) + Date.now().toString(16);
}

function normalizeJournal(j) {
  return {
    id: j?.id || uid(),
    name: j?.name || "Untitled Journal",
    editorValue: j?.editorValue || DEFAULT_EDITOR,
    vars: j?.vars || DEFAULT_VARS,
    videoSrc: j?.videoSrc || null,
    generatedModel: j?.generatedModel || null,
    generatedTopic: j?.generatedTopic || null,
    simConfig: j?.simConfig || null,
    sceneCode: j?.sceneCode || null,
    accuracyLog: Array.isArray(j?.accuracyLog) ? j.accuracyLog : [],
    lastVisualAccuracy: j?.lastVisualAccuracy ?? null,
    topic: j?.topic || "",
    quality: j?.quality || "thinking",
    // ── New fields ──────────────────────────────────────────────────────────
    // Active tab in the left panel
    activeTab: j?.activeTab || "notes",
    // AI-generated Python script for this simulation
    pythonScript: j?.pythonScript || null,
    // Structured equations extracted & generated by AI
    equations: Array.isArray(j?.equations) ? j.equations : [],
    // Uploaded source documents
    sources: Array.isArray(j?.sources) ? j.sources : [],
    // Compiled wiki article for this journal's topic
    wikiArticle: j?.wikiArticle || null,
    // Whether artifacts (python, equations) are currently being generated
    artifactsGenerating: false,
  };
}

function loadFromLS() {
  if (typeof window === "undefined") return null;
  try {
    let v2Raw = window.localStorage.getItem("fulcrum.journals.v2");
    if (!v2Raw) {
      v2Raw = window.localStorage.getItem("loomin.journals.v2");
    }

    let v1Raw = window.localStorage.getItem("fulcrum.journals.v1");
    if (!v1Raw) {
      v1Raw = window.localStorage.getItem("loomin.journals.v1");
    }

    const v2 = v2Raw ? JSON.parse(v2Raw) : null;
    const v1 = v1Raw ? JSON.parse(v1Raw) : null;

    const v2Count = v2?.journals?.length ?? 0;
    const v1Count = v1?.journals?.length ?? 0;

    // If v1 has real journals (more than the default 1 seed), and v2 either doesn't
    // exist or only has the seed journal, restore from v1 and merge any v2 journals on top.
    if (v1Count > 1 && v1Count >= v2Count) {
      const merged = {
        ...v1,
        journals: [
          ...v1.journals,
          // Append any v2 journals that don't already exist in v1
          ...(v2?.journals ?? []).filter(
            (j2) => !v1.journals.some((j1) => j1.id === j2.id)
          ),
        ],
        activeId: v2?.activeId || v1.activeId,
      };
      // Promote merged result to v2 so we don't re-merge on next load
      window.localStorage.setItem("fulcrum.journals.v2", JSON.stringify(merged));
      return merged;
    }

    if (v2Count > 0) return v2;
    if (v1Count > 0) return v1;
    return null;
  } catch { return null; }
}

function saveToLS(state) {
  if (typeof window === "undefined") return;
  // Strip non-serializable / large fields before persisting
  const journals = state.journals.map((j) => {
    const { artifactsGenerating, ...rest } = j;
    return rest;
  });
  const payload = { journals, activeId: state.activeId };
  try {
    window.localStorage.setItem("fulcrum.journals.v2", JSON.stringify(payload));
  } catch { /* quota exceeded — skip */ }
}

const seedJournals = [normalizeJournal({ id: "default", name: "Welcome", editorValue: DEFAULT_EDITOR, vars: DEFAULT_VARS })];

export const useFulcrumStore = create((set, get) => ({
  journals: seedJournals,
  activeId: "default",
  hasUpdated: false,

  updateFromStorage: () => {
    const saved = loadFromLS();
    if (!saved?.journals?.length) {
      set({ hasUpdated: true });
      return;
    }
    set({ journals: saved.journals.map(normalizeJournal), activeId: saved.activeId, hasUpdated: true });
  },

  createJournal: (name = "New Project") => {
    const j = normalizeJournal({ id: uid(), name, editorValue: DEFAULT_EDITOR, vars: { Scene_Mode: -1 } });
    set((s) => ({ journals: [j, ...s.journals], activeId: j.id }));
    saveToLS(get());
  },

  renameJournal: (id, name) => {
    set((s) => ({ journals: s.journals.map((j) => j.id === id ? { ...j, name: name || "Untitled" } : j) }));
    saveToLS(get());
  },

  setEditorValue: (value) => {
    const { activeId } = get();
    set((s) => ({ journals: s.journals.map((j) => j.id === activeId ? { ...j, editorValue: value } : j) }));
    saveToLS(get());
  },

  setVars: (varsPatch) => {
    const { activeId } = get();
    set((s) => ({ journals: s.journals.map((j) => j.id === activeId ? { ...j, vars: varsPatch } : j) }));
    saveToLS(get());
  },

  mergeVar: (key, value) => {
    const { activeId } = get();
    set((s) => ({
      journals: s.journals.map((j) =>
        j.id === activeId ? { ...j, vars: { ...j.vars, [key]: value } } : j
      ),
    }));
    saveToLS(get());
  },

  setVideo: (url) => {
    const { activeId } = get();
    set((s) => ({ journals: s.journals.map((j) => j.id === activeId ? { ...j, videoSrc: url } : j) }));
    saveToLS(get());
  },

  setGeneratedModel: (model, topic) => {
    const { activeId } = get();
    set((s) => ({ journals: s.journals.map((j) => j.id === activeId ? { ...j, generatedModel: model, generatedTopic: topic } : j) }));
    saveToLS(get());
  },

  clearGeneratedModel: () => {
    const { activeId } = get();
    set((s) => ({ journals: s.journals.map((j) => j.id === activeId ? { ...j, generatedModel: null, generatedTopic: null } : j) }));
    saveToLS(get());
  },

  setSimConfig: (config) => {
    const { activeId } = get();
    set((s) => ({ journals: s.journals.map((j) => j.id === activeId ? { ...j, simConfig: config } : j) }));
    saveToLS(get());
  },

  setSceneCode: (code) => {
    const { activeId } = get();
    set((s) => ({ journals: s.journals.map((j) => j.id === activeId ? { ...j, sceneCode: code } : j) }));
    saveToLS(get());
  },

  recordVisualAccuracy: (accurate, topic, simType) => {
    const { activeId } = get();
    const entry = { accurate: !!accurate, ts: Date.now(), topic: String(topic || "").slice(0, 200), simType: simType || "" };
    set((s) => ({
      journals: s.journals.map((j) =>
        j.id === activeId ? { ...j, accuracyLog: [...(j.accuracyLog || []), entry].slice(-80), lastVisualAccuracy: accurate ? "accurate" : "inaccurate" } : j
      ),
    }));
    saveToLS(get());
    if (typeof window === "undefined") return;
    try {
      const raw = window.localStorage.getItem("fulcrum.accuracy.global.v1") || window.localStorage.getItem("loomin.accuracy.global.v1");
      const g = raw ? JSON.parse(raw) : [];
      g.push(entry);
      window.localStorage.setItem("fulcrum.accuracy.global.v1", JSON.stringify(g.slice(-120)));
    } catch { /* ignore */ }
  },

  setTopic: (topic) => {
    const { activeId } = get();
    set((s) => ({ journals: s.journals.map((j) => j.id === activeId ? { ...j, topic } : j) }));
    saveToLS(get());
  },

  setQuality: (quality) => {
    const { activeId } = get();
    set((s) => ({ journals: s.journals.map((j) => j.id === activeId ? { ...j, quality } : j) }));
    saveToLS(get());
  },

  setActive: (id) => { set({ activeId: id }); saveToLS(get()); },

  deleteJournal: (id) => {
    const { journals } = get();
    if (journals.length <= 1) return;
    const next = journals.filter((j) => j.id !== id);
    set({ journals: next, activeId: next[0].id });
    saveToLS(get());
  },

  // ── New actions ────────────────────────────────────────────────────────────

  setActiveTab: (tab) => {
    const { activeId } = get();
    set((s) => ({ journals: s.journals.map((j) => j.id === activeId ? { ...j, activeTab: tab } : j) }));
    // Don't save tab to LS — ephemeral UI state
  },

  setPythonScript: (script) => {
    const { activeId } = get();
    set((s) => ({ journals: s.journals.map((j) => j.id === activeId ? { ...j, pythonScript: script } : j) }));
    saveToLS(get());
  },

  setEquations: (equations) => {
    const { activeId } = get();
    set((s) => ({ journals: s.journals.map((j) => j.id === activeId ? { ...j, equations: equations || [] } : j) }));
    saveToLS(get());
  },

  setArtifactsGenerating: (generating) => {
    const { activeId } = get();
    set((s) => ({
      journals: s.journals.map((j) => j.id === activeId ? { ...j, artifactsGenerating: generating } : j),
    }));
  },

  addSource: (source) => {
    const { activeId } = get();
    set((s) => ({
      journals: s.journals.map((j) =>
        j.id === activeId ? { ...j, sources: [...(j.sources || []), source] } : j
      ),
    }));
    saveToLS(get());
  },

  removeSource: (sourceId) => {
    const { activeId } = get();
    set((s) => ({
      journals: s.journals.map((j) =>
        j.id === activeId ? { ...j, sources: (j.sources || []).filter((s) => s.id !== sourceId) } : j
      ),
    }));
    saveToLS(get());
  },

  setWikiArticle: (article) => {
    const { activeId } = get();
    set((s) => ({ journals: s.journals.map((j) => j.id === activeId ? { ...j, wikiArticle: article } : j) }));
    saveToLS(get());
  },
}));
